version: '3'
services:
    caddy:
        image: caddy:2
        restart: unless-stopped
        volumes:
        - /home/rcos/config/Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        ports:
        - "80:80"
        - "443:443"

    hasura:
        image: hasura/graphql-engine
        restart: unless-stopped
        environment:
            # https://hasura.io/docs/1.0/graphql/core/deployment/graphql-engine-flags/reference.html
            HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "web_anon"
            HASURA_GRAPHQL_DATABASE_URL: "${DATABASE_URL}"
            HASURA_GRAPHQL_DEV_MODE: "false"
            HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
            HASURA_GRAPHQL_JWT_SECRET: "{ \"type\": \"HS256\", \"key\": \"${RCOS_JWT_SECRET}\" }"
            HASURA_GRAPHQL_LOG_LEVEL: "warn"
            HASURA_GRAPHQL_ADMIN_SECRET: "${RCOS_ADMIN_SECRET}"

    wikijs:
        image: requarks/wiki:2
        restart: unless-stopped
        volumes:
        - /home/rcos/config/wiki.yml:/wiki/config.yml
        - /home/rcos/config/db-cert.crt:/wiki/db-cert.crt

    telescope:
        image: docker.pkg.github.com/rcos/telescope/telescope:0.5.2
        restart: unless-stopped
        depends_on:
            - hasura
        volumes:
          # The redacted telescope config file is included in this repo. 
          # Full dockumentation of all of the options is available at 
          # https://github.com/rcos/Telescope/blob/master/config_example.toml.
          - "/home/rcos/config/telescope-config.toml:/telescope/config.toml"

volumes:
    caddy_data:

